export const AUTH_USER_OK = 'AUTH_USER_OK';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const SET_NOTIFICATIONS_SUCCESS = 'SET_NOTIFICATIONS_SUCCESS';
export const SET_NOTIFICATIONS_UNAUTHORIZED = 'SET_NOTIFICATIONS_UNAUTHORIZED';
export const SET_NOTIFICATIONS_AUTHORIZED = 'SET_NOTIFICATIONS_AUTHORIZED';
export const UNSET_NOTIFICATIONS_UNAUTHORIZED = 'UNSET_NOTIFICATIONS_UNAUTHORIZED';
export const UNSET_NOTIFICATIONS_AUTHORIZED = 'UNSET_NOTIFICATIONS_AUTHORIZED';
