export const AUTH_USER_OK = 'AUTH_USER_OK';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const AUTH_GET_LOCAL_TOKEN = 'AUTH_GET_LOCAL_TOKEN';
export const AUTH_GET_LOCAL_USER_DETAILS = 'AUTH_GET_LOCAL_USER_DETAILS';
export const AUTH_SET_LOCAL_USER_DETAILS = 'AUTH_SET_LOCAL_USER_DETAILS';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';

export const UNSET_NOTIFICATION_CRUD = 'UNSET_NOTIFICATIONS_CRUD';
export const SET_NOTIFICATIONS_SUCCESS = 'SET_NOTIFICATIONS_SUCCESS';
export const SET_NOTIFICATIONS_ERRORS = 'SET_NOTIFICATIONS_ERRORS';
export const SET_NOTIFICATIONS_UNAUTHORIZED = 'SET_NOTIFICATIONS_UNAUTHORIZED';
export const SET_NOTIFICATIONS_AUTHORIZED = 'SET_NOTIFICATIONS_AUTHORIZED';
export const UNSET_NOTIFICATIONS_UNAUTHORIZED = 'UNSET_NOTIFICATIONS_UNAUTHORIZED';
export const UNSET_NOTIFICATIONS_AUTHORIZED = 'UNSET_NOTIFICATIONS_AUTHORIZED';

export const NAVIGATION_GOTO = 'NAVIGATION_GOTO';

export const REQUIREMENTS_CATEGORIES_SET_DATA = 'REQUIREMENTS_CATEGORIES_SET_DATA';
export const REQUIREMENTS_CATEGORIES_SET_COLUMN_NAMES = 'REQUIREMENTS_CATEGORIES_SET_COLUMN_NAMES';
export const REQUIREMENTS_CATEGORIES_LIST = 'REQUIREMENTS_CATEGORIES_LIST';
export const REQUIREMENTS_CATEGORIES_SAVE = 'REQUIREMENTS_CATEGORIES_SAVE';
export const REQUIREMENTS_CATEGORIES_DELETE = 'REQUIREMENTS_CATEGORIES_DELETE';

export const REQUIREMENTS_GENRES_SET_DATA = 'REQUIREMENTS_GENRES_SET_DATA';
export const REQUIREMENTS_GENRES_LIST = 'REQUIREMENTS_GENRES_LIST';
export const REQUIREMENTS_GENRES_SAVE = 'REQUIREMENTS_GENRES_SAVE';
export const REQUIREMENTS_GENRES_DELETE = 'REQUIREMENTS_GENRES_DELETE';

export const MOVIES_SET_DATA = 'MOVIES_SET_DATA';
export const MOVIES_LIST = 'MOVIES_LIST';
export const MOVIES_SAVE = 'MOVIES_SAVE';
export const MOVIES_DELETE = 'MOVIES_DELETE';
